# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Theodoros Georgakopoulos
title: Computer Engineer
email: tgeorgako@gmail.com
website: tgeorgako.github.io/
PDF: https://tgeorgako.github.io/resume.pdf

# Social links
twitter_username: 
github_username:  tgeorgako
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: theodoros-georgakopoulos
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Theodoros Georgakopoulos and I am a computer engineer. I enjoy building and troubleshooting systems and creating applications. Throughout my career I have worked at many companies and institutions gaining teamwork and leadership skills.

  I am most skilled in building websites and handling complicated IT problems.

# Projects Section
# projects_title: Projects


# Education Section
# educaton_title: Education

# Experience Section
# experience_title: Experience

# More Section
# more_title: Skills
more_content: | # this will include new lines to allow paragraphs
    - Excellent use and support of operating systems, office applications and services (MS Windows, Linux, MacOS, MS Office).
    - Digital Marketing (Google Adwords, Business Facebook).
    - Excellent use and configuration of smartphone software iOS, Android, Windows Mobile.
    - Technical support for computers and mobile systems telephones, closed surveillance systems, telephony.
    - Programming knowledge (PHP, Javascipt, Java, Matlab).
    - Communication and teamwork skills
    - Website Design and Management (Plesk, Wordpress, HTML5, CSS, Javascript, MySQL)
    - Driving licence B

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
