# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Theodoros Georgakopoulos
title: Computer Engineer
email: tgeorgako@gmail.com
website: https://tgeorgako.github.io/

# Social links
#twitter_username: facespics
github_username:  tgeorgako
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: theodoros-georgakopoulos
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Theodoros Georgakopoulos and I am a computer engineer. I enjoy building and troubleshooting systems and creating applications. Throughout my career I have worked at many companies and institutions gaining teamwork and leadership skills.

  I am most skilled in building websites and handling complicated IT problems.

# Projects Section
# projects_title: Projects


# Education Section
# educaton_title: Education

# Experience Section
# experience_title: Experience

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
