version: 2.1
jobs:
  build:
    docker: 
      - image: danteev/texlive # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: cd .. # run the `cd` command
     # - run: chmod +x PdfScript.sh
    #  - run: ./PdfScript.sh # run the `script` command
      - run: make # run the `make` command
      - run: echo "Success!!!" # run the `echo` command